### ISSUE TITLE
training error when calculate loss

### ISSUE THREAD

**Issue by SeaFu** [likui01/LDNet#4]
Dear likui01,
I'm interested in your work. I have a question about using the DET dataset to training model. The error means the dimension is different between labels and outputs. The dimension of outputs is 4x5x256x256 tensor, 5 is the number of class. In your research is 'background','lane1','lane2','lane3' and 'lane4'. But the dimension of labels is 4x1x256x256. How can I to solve it.
![Spyder (Python 3 8)_036](https://user-images.githubusercontent.com/42667670/182322647-0b82c5ed-6a8a-44b5-a872-feac80cb138d.png)

**Comment by munirfarzeen** [comment]
kindly read the loss function and hopefully, you will understand how it works. It handles the labels through one-hot encoding.

**Comment by SeaFu** [comment]
I Solved it, the problem is not about the loss function and one-hot encoding.

**Comment by SeaFu** [comment]
I Solved it, the problem is not about the loss function and one-hot encoding.
